// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: f3d758c6927d

//! Generated Phoenix channel contract tests.
mod support;
use archastro::generated::*;
use futures_util::StreamExt;

#[test]
fn generated_support_is_linked() {
    support::mark_all_used();
}

#[tokio::test]
#[serial_test::serial]
#[ignore = "requires channel harness"]
async fn api_activity_feed_channel_join_agent_join() {
    let harness = support::harness().await;
    let topic = "api:activity_feed:agent:test-id";
    harness.register_channel(topic, &[], &[]).await;
    let socket = harness.socket().await;
    let channel = ApiActivityFeedChannel::join_agent(&socket, "test-id")
        .await
        .expect("join channel");
    channel.leave().await.expect("leave channel");
}

#[tokio::test]
#[serial_test::serial]
#[ignore = "requires channel harness"]
async fn api_activity_feed_channel_join_org_join() {
    let harness = support::harness().await;
    let topic = "api:activity_feed:org:test-id";
    harness.register_channel(topic, &[], &[]).await;
    let socket = harness.socket().await;
    let channel = ApiActivityFeedChannel::join_org(&socket, "test-id")
        .await
        .expect("join channel");
    channel.leave().await.expect("leave channel");
}

#[tokio::test]
#[serial_test::serial]
#[ignore = "requires channel harness"]
async fn api_activity_feed_channel_messages_and_pushes() {
    let harness = support::harness().await;
    let topic = "api:activity_feed:agent:test-id";
    harness
        .register_channel(topic, &["list_entries"], &["new_entry"])
        .await;
    let socket = harness.socket().await;
    let channel = ApiActivityFeedChannel::join_agent(&socket, "test-id")
        .await
        .expect("join channel");
    let message_0: ApiActivityFeedChannelListEntriesInput =
        serde_json::from_str(r#"{}"#).expect("valid message input");
    channel
        .list_entries(&message_0)
        .await
        .expect("channel push");
    let mut push_0 = channel.subscribe_new_entry();
    push_0
        .next()
        .await
        .expect("server push")
        .expect("decode server push");
    channel.leave().await.expect("leave channel");
}

#[tokio::test]
#[serial_test::serial]
#[ignore = "requires channel harness"]
async fn api_chat_channel_join_team_thread_join() {
    let harness = support::harness().await;
    let topic = "api:chat:team:test-id:thread:test-id";
    let join_params: ApiChatChannelJoinTeamThreadParams =
        serde_json::from_str(r#"{}"#).expect("valid join params");
    harness.register_channel(topic, &[], &[]).await;
    let socket = harness.socket().await;
    let channel = ApiChatChannel::join_team_thread(&socket, "test-id", "test-id", &join_params)
        .await
        .expect("join channel");
    channel.leave().await.expect("leave channel");
}

#[tokio::test]
#[serial_test::serial]
#[ignore = "requires channel harness"]
async fn api_chat_channel_join_team_keyed_join() {
    let harness = support::harness().await;
    let topic = "api:chat:team:test-id:key:test-key";
    let join_params: ApiChatChannelJoinTeamKeyedParams =
        serde_json::from_str(r#"{}"#).expect("valid join params");
    harness.register_channel(topic, &[], &[]).await;
    let socket = harness.socket().await;
    let channel = ApiChatChannel::join_team_keyed(&socket, "test-id", "test-key", &join_params)
        .await
        .expect("join channel");
    channel.leave().await.expect("leave channel");
}

#[tokio::test]
#[serial_test::serial]
#[ignore = "requires channel harness"]
async fn api_chat_channel_join_team_transient_join() {
    let harness = support::harness().await;
    let topic = "api:chat:team:test-id:transient:test-key";
    let join_params: ApiChatChannelJoinTeamTransientParams =
        serde_json::from_str(r#"{}"#).expect("valid join params");
    harness.register_channel(topic, &[], &[]).await;
    let socket = harness.socket().await;
    let channel = ApiChatChannel::join_team_transient(&socket, "test-id", "test-key", &join_params)
        .await
        .expect("join channel");
    channel.leave().await.expect("leave channel");
}

#[tokio::test]
#[serial_test::serial]
#[ignore = "requires channel harness"]
async fn api_chat_channel_join_user_thread_join() {
    let harness = support::harness().await;
    let topic = "api:chat:user:thread:test-id";
    let join_params: ApiChatChannelJoinUserThreadParams =
        serde_json::from_str(r#"{}"#).expect("valid join params");
    harness.register_channel(topic, &[], &[]).await;
    let socket = harness.socket().await;
    let channel = ApiChatChannel::join_user_thread(&socket, "test-id", &join_params)
        .await
        .expect("join channel");
    channel.leave().await.expect("leave channel");
}

#[tokio::test]
#[serial_test::serial]
#[ignore = "requires channel harness"]
async fn api_chat_channel_join_user_keyed_join() {
    let harness = support::harness().await;
    let topic = "api:chat:user:key:test-key";
    let join_params: ApiChatChannelJoinUserKeyedParams =
        serde_json::from_str(r#"{}"#).expect("valid join params");
    harness.register_channel(topic, &[], &[]).await;
    let socket = harness.socket().await;
    let channel = ApiChatChannel::join_user_keyed(&socket, "test-key", &join_params)
        .await
        .expect("join channel");
    channel.leave().await.expect("leave channel");
}

#[tokio::test]
#[serial_test::serial]
#[ignore = "requires channel harness"]
async fn api_chat_channel_join_user_transient_join() {
    let harness = support::harness().await;
    let topic = "api:chat:user:transient:test-key";
    let join_params: ApiChatChannelJoinUserTransientParams =
        serde_json::from_str(r#"{}"#).expect("valid join params");
    harness.register_channel(topic, &[], &[]).await;
    let socket = harness.socket().await;
    let channel = ApiChatChannel::join_user_transient(&socket, "test-key", &join_params)
        .await
        .expect("join channel");
    channel.leave().await.expect("leave channel");
}

#[tokio::test]
#[serial_test::serial]
#[ignore = "requires channel harness"]
async fn api_chat_channel_messages_and_pushes() {
    let harness = support::harness().await;
    let topic = "api:chat:team:test-id:thread:test-id";
    let join_params: ApiChatChannelJoinTeamThreadParams =
        serde_json::from_str(r#"{}"#).expect("valid join params");
    harness
        .register_channel(
            topic,
            &[
                "api:chat:fork_thread",
                "api:chat:mark_thread_read",
                "api:chat:list_messages",
                "api:chat:load_more_messages",
                "api:chat:post_message",
                "api:chat:post_simple_message",
                "api:chat:edit_message",
                "api:chat:delete_message",
                "api:chat:add_reaction",
                "api:chat:remove_reaction",
                "api:chat:typing",
            ],
            &[
                "message_added",
                "message_updated",
                "thread_event",
                "system_event",
                "typing",
            ],
        )
        .await;
    let socket = harness.socket().await;
    let channel = ApiChatChannel::join_team_thread(&socket, "test-id", "test-id", &join_params)
        .await
        .expect("join channel");
    let message_0: ApiChatChannelApiChatForkThreadInput =
        serde_json::from_str(r#"{"message_id":"test-id"}"#).expect("valid message input");
    channel
        .api_chat_fork_thread(&message_0)
        .await
        .expect("channel push");
    let message_1: ApiChatChannelApiChatMarkThreadReadInput =
        serde_json::from_str(r#"{"message_id":"test-id"}"#).expect("valid message input");
    channel
        .api_chat_mark_thread_read(&message_1)
        .await
        .expect("channel push");
    channel
        .api_chat_list_messages()
        .await
        .expect("channel push");
    let message_3: ApiChatChannelApiChatLoadMoreMessagesInput =
        serde_json::from_str(r#"{}"#).expect("valid message input");
    channel
        .api_chat_load_more_messages(&message_3)
        .await
        .expect("channel push");
    let message_4: ApiChatChannelApiChatPostMessageInput =
        serde_json::from_str(r#"{"content":"test-value"}"#).expect("valid message input");
    channel
        .api_chat_post_message(&message_4)
        .await
        .expect("channel push");
    let message_5: ApiChatChannelApiChatPostSimpleMessageInput =
        serde_json::from_str(r#"{}"#).expect("valid message input");
    channel
        .api_chat_post_simple_message(&message_5)
        .await
        .expect("channel push");
    let message_6: ApiChatChannelApiChatEditMessageInput =
        serde_json::from_str(r#"{"content":"test-value","message_id":"test-id"}"#)
            .expect("valid message input");
    channel
        .api_chat_edit_message(&message_6)
        .await
        .expect("channel push");
    let message_7: ApiChatChannelApiChatDeleteMessageInput =
        serde_json::from_str(r#"{"message_id":"test-id"}"#).expect("valid message input");
    channel
        .api_chat_delete_message(&message_7)
        .await
        .expect("channel push");
    let message_8: ApiChatChannelApiChatAddReactionInput =
        serde_json::from_str(r#"{"emoji":"test-value","message_id":"test-id"}"#)
            .expect("valid message input");
    channel
        .api_chat_add_reaction(&message_8)
        .await
        .expect("channel push");
    let message_9: ApiChatChannelApiChatRemoveReactionInput =
        serde_json::from_str(r#"{"emoji":"test-value","message_id":"test-id"}"#)
            .expect("valid message input");
    channel
        .api_chat_remove_reaction(&message_9)
        .await
        .expect("channel push");
    let message_10: ApiChatChannelApiChatTypingInput =
        serde_json::from_str(r#"{"is_typing":true}"#).expect("valid message input");
    channel
        .api_chat_typing(&message_10)
        .await
        .expect("channel push");
    let mut push_0 = channel.subscribe_message_added();
    push_0
        .next()
        .await
        .expect("server push")
        .expect("decode server push");
    let mut push_1 = channel.subscribe_message_updated();
    push_1
        .next()
        .await
        .expect("server push")
        .expect("decode server push");
    let mut push_2 = channel.subscribe_thread_event();
    push_2
        .next()
        .await
        .expect("server push")
        .expect("decode server push");
    let mut push_3 = channel.subscribe_system_event();
    push_3
        .next()
        .await
        .expect("server push")
        .expect("decode server push");
    let mut push_4 = channel.subscribe_typing();
    push_4
        .next()
        .await
        .expect("server push")
        .expect("decode server push");
    channel.leave().await.expect("leave channel");
}

#[tokio::test]
#[serial_test::serial]
#[ignore = "requires channel harness"]
async fn api_object_channel_join_by_id_join() {
    let harness = support::harness().await;
    let topic = "api:object:test-id";
    let join_params: ApiObjectChannelJoinByIdParams =
        serde_json::from_str(r#"{}"#).expect("valid join params");
    harness.register_channel(topic, &[], &[]).await;
    let socket = harness.socket().await;
    let channel = ApiObjectChannel::join_by_id(&socket, "test-id", &join_params)
        .await
        .expect("join channel");
    channel.leave().await.expect("leave channel");
}

#[tokio::test]
#[serial_test::serial]
#[ignore = "requires channel harness"]
async fn api_object_channel_join_by_row_key_join() {
    let harness = support::harness().await;
    let topic = "api:object:test-value:test-key";
    let join_params: ApiObjectChannelJoinByRowKeyParams =
        serde_json::from_str(r#"{}"#).expect("valid join params");
    harness.register_channel(topic, &[], &[]).await;
    let socket = harness.socket().await;
    let channel =
        ApiObjectChannel::join_by_row_key(&socket, "test-value", "test-key", &join_params)
            .await
            .expect("join channel");
    channel.leave().await.expect("leave channel");
}

#[tokio::test]
#[serial_test::serial]
#[ignore = "requires channel harness"]
async fn api_object_channel_messages_and_pushes() {
    let harness = support::harness().await;
    let topic = "api:object:test-id";
    let join_params: ApiObjectChannelJoinByIdParams =
        serde_json::from_str(r#"{}"#).expect("valid join params");
    harness
        .register_channel(
            topic,
            &["update_fields", "save", "presence_update"],
            &[
                "object_updated",
                "object_created",
                "object_deleted",
                "presence_updated",
                "presence_left",
                "access_revoked",
            ],
        )
        .await;
    let socket = harness.socket().await;
    let channel = ApiObjectChannel::join_by_id(&socket, "test-id", &join_params)
        .await
        .expect("join channel");
    let message_0: ApiObjectChannelUpdateFieldsInput =
        serde_json::from_str(r#"{"fields":{}}"#).expect("valid message input");
    channel
        .update_fields(&message_0)
        .await
        .expect("channel push");
    channel.save().await.expect("channel push");
    let message_2: ApiObjectChannelPresenceUpdateInput =
        serde_json::from_str(r#"{"presence":{}}"#).expect("valid message input");
    channel
        .presence_update(&message_2)
        .await
        .expect("channel push");
    let mut push_0 = channel.subscribe_object_updated();
    push_0
        .next()
        .await
        .expect("server push")
        .expect("decode server push");
    let mut push_1 = channel.subscribe_object_created();
    push_1
        .next()
        .await
        .expect("server push")
        .expect("decode server push");
    let mut push_2 = channel.subscribe_object_deleted();
    push_2
        .next()
        .await
        .expect("server push")
        .expect("decode server push");
    let mut push_3 = channel.subscribe_presence_updated();
    push_3
        .next()
        .await
        .expect("server push")
        .expect("decode server push");
    let mut push_4 = channel.subscribe_presence_left();
    push_4
        .next()
        .await
        .expect("server push")
        .expect("decode server push");
    let mut push_5 = channel.subscribe_access_revoked();
    push_5
        .next()
        .await
        .expect("server push")
        .expect("decode server push");
    channel.leave().await.expect("leave channel");
}

#[tokio::test]
#[serial_test::serial]
#[ignore = "requires channel harness"]
async fn api_tasks_channel_join_thread_join() {
    let harness = support::harness().await;
    let topic = "api:tasks:thread:test-id";
    harness.register_channel(topic, &[], &[]).await;
    let socket = harness.socket().await;
    let channel = ApiTasksChannel::join_thread(&socket, "test-id")
        .await
        .expect("join channel");
    channel.leave().await.expect("leave channel");
}

#[tokio::test]
#[serial_test::serial]
#[ignore = "requires channel harness"]
async fn api_tasks_channel_messages_and_pushes() {
    let harness = support::harness().await;
    let topic = "api:tasks:thread:test-id";
    harness
        .register_channel(topic, &[], &["tasks_updated"])
        .await;
    let socket = harness.socket().await;
    let channel = ApiTasksChannel::join_thread(&socket, "test-id")
        .await
        .expect("join channel");
    let mut push_0 = channel.subscribe_tasks_updated();
    push_0
        .next()
        .await
        .expect("server push")
        .expect("decode server push");
    channel.leave().await.expect("leave channel");
}
