// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: e2aa44ffa5c3

//! Generated SSE contract tests.
mod support;
use archastro::generated::*;
use futures_util::StreamExt;

#[test]
fn generated_support_is_linked() {
    support::mark_all_used();
}

#[tokio::test]
#[serial_test::serial]
#[ignore = "requires channel harness"]
async fn get_api_v1_agent_routine_runs_agent_routine_run_stream_events() {
    let harness = support::harness().await;
    harness
        .register_stream(
            "GET /api/v1/agent_routine_runs/{agent_routine_run}/stream",
            &["run_update"],
        )
        .await;
    let client = harness.client();
    let mut stream = client
        .v1()
        .agent_routine_runs()
        .stream("test-value")
        .await
        .expect("open stream");
    let mut count = 0usize;
    while let Some(event) = stream.next().await {
        event.expect("decode event");
        count += 1;
        if count == 1 {
            break;
        }
    }
    assert_eq!(count, 1);
}

#[tokio::test]
#[serial_test::serial]
#[ignore = "requires channel harness"]
async fn get_api_v1_agent_sessions_agent_session_stream_events() {
    let harness = support::harness().await;
    harness
        .register_stream(
            "GET /api/v1/agent_sessions/{agent_session}/stream",
            &["session_update"],
        )
        .await;
    let client = harness.client();
    let mut stream = client
        .v1()
        .agent_sessions()
        .stream("test-value")
        .await
        .expect("open stream");
    let mut count = 0usize;
    while let Some(event) = stream.next().await {
        event.expect("decode event");
        count += 1;
        if count == 1 {
            break;
        }
    }
    assert_eq!(count, 1);
}

#[tokio::test]
#[serial_test::serial]
#[ignore = "requires channel harness"]
async fn get_api_v1_automation_runs_automation_run_stream_events() {
    let harness = support::harness().await;
    harness
        .register_stream(
            "GET /api/v1/automation_runs/{automation_run}/stream",
            &["run_update"],
        )
        .await;
    let client = harness.client();
    let mut stream = client
        .v1()
        .automation_runs()
        .stream("test-value")
        .await
        .expect("open stream");
    let mut count = 0usize;
    while let Some(event) = stream.next().await {
        event.expect("decode event");
        count += 1;
        if count == 1 {
            break;
        }
    }
    assert_eq!(count, 1);
}

#[tokio::test]
#[serial_test::serial]
#[ignore = "requires channel harness"]
async fn post_api_v1_ai_chat_completions_stream_events() {
    let harness = support::harness().await;
    harness
        .register_stream(
            "POST /api/v1/ai/chat/completions/stream",
            &[
                "done",
                "error",
                "message_complete",
                "message_delta",
                "thinking_delta",
                "tool_call_delta",
                "tool_result",
            ],
        )
        .await;
    let client = harness.client();
    let body: PostApiV1AiChatCompletionsStreamInput = serde_json::from_str(r#"{"messages":[{"content":"How can I help you today?","content_parts":[{}],"resume_token":"string","role":"user","tool_calls":[{"arguments":{},"id":"string","name":"Example Name","thought_signature":"string"}],"tool_results":[{"content":"string","id":"string","name":"Example Name"}]}],"opts":{"max_tokens":1,"model":"string","server_tools":[{}],"temperature":1,"tool_choice":"string","tools":[{"function":{"description":"An example description.","name":"Example Name","parameters":{}},"type":"function"}]}}"#).expect("valid generated body");
    let mut stream = client
        .v1()
        .ai()
        .chat()
        .completions()
        .stream()
        .create(&body)
        .await
        .expect("open stream");
    let mut count = 0usize;
    while let Some(event) = stream.next().await {
        event.expect("decode event");
        count += 1;
        if count == 7 {
            break;
        }
    }
    assert_eq!(count, 7);
}
